# Generated by Django 2.2.3 on 2020-08-01 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apitest', '0005_apiargument_case_caseargument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRunRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='运行时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Case', verbose_name='所属用例')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CaseApiRunRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='请求的url！')),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10, verbose_name='请求方式')),
                ('headers', models.TextField(null=True, verbose_name='请求头')),
                ('data', models.TextField(null=True, verbose_name='提交的数据')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='运行的时间')),
                ('return_code', models.CharField(max_length=10, verbose_name='返回的code')),
                ('return_content', models.TextField(null=True, verbose_name='返回的内容')),
                ('api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.Api', verbose_name='关联的API')),
                ('case_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_records', to='apitest.CaseRunRecord', verbose_name='关联的case_record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行命令的人')),
            ],
        ),
    ]
