# Generated by Django 2.2.3 on 2020-08-02 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apitest', '0006_caseapirunrecord_caserunrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('expr', models.CharField(max_length=200, verbose_name='任务执行表达式')),
                ('status', models.SmallIntegerField(choices=[(1, 1), (2, 2)], default=2, verbose_name='任务的状态')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Case', verbose_name='定时执行的用例')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='apitest.Project', verbose_name='所属的项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务创建者')),
            ],
        ),
    ]
